<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillSeeder extends Seeder
{
    public function run()
    {
        DB::table('skills')->insert([
           [
           'name' => 'Weaponsmithing',
           'description' => '',
           'order' => 10,
           'skill_type_id' => 1,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Armoring',
           'description' => '',
           'order' => 20,
           'skill_type_id' => 1,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Engineering',
           'description' => '',
           'order' => 30,
           'skill_type_id' => 1,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Jewelcrafting',
           'description' => '',
           'order' => 40,
           'skill_type_id' => 1,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Arcana',
           'description' => '',
           'order' => 50,
           'skill_type_id' => 1,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Cooking',
           'description' => '',
           'order' => 60,
           'skill_type_id' => 1,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Furnishing',
           'description' => '',
           'order' => 70,
           'skill_type_id' => 1,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           // refining
           [
           'name' => 'Smelting',
           'description' => '',
           'order' => 80,
           'skill_type_id' => 2,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Woodworking',
           'description' => '',
           'order' => 90,
           'skill_type_id' => 2,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Leatherworking',
           'description' => '',
           'order' => 100,
           'skill_type_id' => 2,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Weaving',
           'description' => '',
           'order' => 110,
           'skill_type_id' => 2,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Stonecutting',
           'description' => '',
           'order' => 120,
           'skill_type_id' => 2,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           // gathering
           [
           'name' => 'Logging',
           'description' => '',
           'order' => 130,
           'skill_type_id' => 3,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Mining',
           'description' => '',
           'order' => 140,
           'skill_type_id' => 3,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Fishing',
           'description' => '',
           'order' => 150,
           'skill_type_id' => 3,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Harvesting',
           'description' => '',
           'order' => 160,
           'skill_type_id' => 3,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Tracking & Skinning',
           'description' => '',
           'order' => 170,
           'skill_type_id' => 3,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           // weapon mastery
           [
           'name' => 'Sword and Shield',
           'description' => '',
           'order' => 180,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Rapier',
           'description' => '',
           'order' => 190,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Hatchet',
           'description' => '',
           'order' => 200,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Spear',
           'description' => '',
           'order' => 210,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Great Axe',
           'description' => '',
           'order' => 220,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'War Hammer',
           'description' => '',
           'order' => 230,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Bow',
           'description' => '',
           'order' => 240,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Musket',
           'description' => '',
           'order' => 250,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Fire Staff',
           'description' => '',
           'order' => 260,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Life Staff',
           'description' => '',
           'order' => 270,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
           [
           'name' => 'Ice Gauntlet',
           'description' => '',
           'order' => 280,
           'skill_type_id' => 4,
           'created_at' => now(),
           'updated_at' => now(),
           ],
       ]);
    }
}
