    @can('viewAny', \App\Models\Loadout::class)
        <x-dashboard.section
            :title="'Loadout'"
            class=""
        >
            <x-dashboard.view-all-button 
                :class="\App\Models\Loadout::class" 
                :route="route('loadouts.index')"
            />
            @isset($loadout)
                <x-dashboard.view-own-button 
                    :class="\App\Models\Loadout::class" 
                    :route="route('loadouts.show', ['loadout'=>$loadout])"
                    :instance="$loadout"
                />
            @endcan
            <x-dashboard.create-button 
                :class="\App\Models\Loadout::class" 
                :route="route('loadouts.create')"
                :instance="$loadout"
            />
            @isset($loadout)
                <x-dashboard.edit-delete-button 
                    :class="\App\Models\Loadout::class" 
                    :route="route('loadouts.choose')"
                    :instance="$loadout"
                />
            @endisset
        </x-dashboard.section>
@endisset
